name: arctic_pups
description: Convenience application for pet parents.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  carousel_pro: ^0.0.13
  firebase_auth: ^0.11.1+7
  cloud_firestore: ^0.12.5+2
  rxdart: ^0.22.0
  #cached_network_image:
  firebase_core: ^0.4.0+6
  intl: ^0.15.8
  google_sign_in: ^4.0.2
  firebase_database: ^3.0.3
  firebase_storage: ^3.0.2
  shared_preferences: ^0.5.3+1
  bottom_navy_bar: 5.1.0
  fancy_bottom_navigation: 0.3.2
  oktoast: 2.1.9
  flutter_facebook_login: ^2.0.1
  flutter_spinkit: ^3.1.0
  persist_theme: ^1.5.1
  image_picker: ^0.6.0+10
  camera: 0.5.2+2
  video_player: 0.10.1+5
  flutter_staggered_grid_view: ^0.3.0
  image_cropper : ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Regular.ttf
        - asset: assets/fonts/Raleway-SemiBold.ttf

    - family: Oxygen
      fonts:
        - asset: assets/fonts/Oxygen-Regular.ttf
        - asset: assets/fonts/Oxygen-Bold.ttf


    - family: DancingScript
      fonts:
        - asset: assets/fonts/DancingScript-Regular.ttf
        - asset: assets/fonts/DancingScript-Bold.ttf

    - family: Pacifico
      fonts:
        - asset: assets/fonts/Pacifico-Regular.ttf